book:
  title: "Fit mit Markdown"
  author: 
   - "Nils Ratnaweera"
   - "Dominic Lüönd"
  date: last-modified
  sidebar: 
    logo: images/zhaw_lsfm_iunr_blau.jpg
  repo-url: https://github.com/Fit-mit-Markdown/Fit-mit-Markdown.github.io
  repo-actions: [edit, issue]  
  chapters: 
    - index.qmd

profile:
  default: full
  group: 
    - [full, statistik]

lang: de
bibliography: references.bib
number-sections: false

format:
  html:
    theme: cosmo
