project:
  type: book
  output-dir: _site-full

book:
  title: "Fit mit Markdown"
  author: 
   - "Nils Ratnaweera"
   - "Dominic Lüönd"
  date: "11/22/2023"
  chapters: 
    - index.qmd


profile:
  group: 
    - [full, statistik]

lang: de
bibliography: references.bib


format:
  html:
    theme: cosmo



