# Einleitung {.unnumbered}

```{r}
#| output: false
#| echo: false
Sys.getenv("QUARTO_PROFILE")

```

**Quarto**, RMarkown und Jupyter Notebooks haben eine Sache gemeinsam. Sie sind *Computational Notebooks*. Das heisst, sie sind eine Mischung aus Fliesstext und Code. Der Fliesstext wird in einer Markupsprache namens Markdown geschrieben, der Code kann in einer beliebigen Programmiersprache geschrieben werden, typischerweise verwendet man Python, R oder Julia. 

Diese *Computational Notebooks* werden mittels einer Software typischerweise in HTML oder PDF konvertiert. Möglich sind aber auch andere Formate wie epub (EBook), Docx und viele mehr. Dieses System eignet sich sehr gut, um Datenanalysen zu dokumentieren und zu publizieren. Es eignet sich aber auch sehr gut, um Unterrichtsmaterialien zu erstellen.

Seit ein paar Jahren verwenden wir **Quarto** für die Bereitstellung von Unterrichtsunterlagen an die Studierenden. Der Umstieg von klassischen Systemen wie Microsoft Word ist nicht ganz einfach. Da wir in vielen Fällen mit anderen Personen zusammenarbeiten, haben wir diese Anleitung geschrieben um den Einstieg zu erleichtern. Mittlerweile sind im Netz zahlreiche Anleitung, Videos und ander Ressourcen verfügbar. Unsere, also die vorliegende Anleitung, soll spezifisch für ZHAW Mitarbeiter hilfreich sein, den Einstieg zu machen. Dabei werden wir punktuell auf solche Ressourcen verweisen, dabei aber sehr spezifisch bleiben.